from tkinter import *
import datetime
root = Tk()
root.title("INCOME AND EXPENSE TRACKER")
root.geometry("450x400")
datelabel = Label(root, text="Date(DD): ", font=("Times", 15)).place(x=20,y=10)
dd = IntVar()
dateent = Entry(root, textvariable=dd, font=("Times", 15)).place(x=110,y=12,width=27)
monthlabel = Label(root, text="Month(MM): ", font=("Times", 15)).place(x=138,y=10)
mm = IntVar()
monthent = Entry(root, textvariable=mm, font=("Times", 15)).place(x=247,y=12,width=27)
yearlabel = Label(root, text="Year(YYYY): ", font=("Times", 15)).place(x=270,y=10)
yy = IntVar()
yearent = Entry(root, textvariable=yy, font=("Times", 15)).place(x=390,y=12,width=50)
acctype = IntVar()
Radiobutton(text="1.Bank Account", font=("Times",15), variable=acctype, value=1).place(x=50,y=50)
Radiobutton(text="2.Cash", font=("Times",15), variable=acctype, value=2).place(x=275,y=50)
amountlabel = Label(root, text="Enter Amount of money", font=("Times", 15)).place(x=105,y=90)
amountinput = StringVar()
amount = Entry(root, font=("Times", 15), textvariable=amountinput).place(x=100,y=130)
cate = IntVar()
Radiobutton(text="Salary", font=("Times",15), variable=cate, value=7).place(x=50,y=160)
Radiobutton(text="Incoming Transfer", font=("Times",15), variable=cate, value=8).place(x=50,y=190)
Radiobutton(text="other income", font=("Times",15), variable=cate, value=9).place(x=50,y=220)
Radiobutton(text="Food and Beverage", font=("Times",15), variable=cate, value=1).place(x=225,y=160)
Radiobutton(text="Transportation and gas", font=("Times",15), variable=cate, value=2).place(x=225,y=190)
Radiobutton(text="Entertainment", font=("Times",15), variable=cate, value=3).place(x=225,y=220)
Radiobutton(text="Sport", font=("Times",15), variable=cate, value=4).place(x=225,y=250)
Radiobutton(text="Investment", font=("Times",15), variable=cate, value=5).place(x=225,y=280)
Radiobutton(text="other expense", font=("Times",15), variable=cate, value=6).place(x=225,y=310)
Add = Button(root, text="Add", height=2, width=10, bg="Cyan").place(x=75,y=350)
exreport = Button(root, text="Report expenses", height=2, width=13, bg="Red").place(x=175,y=350)
inreport = Button(root, text="Report income", height=2, width=13, bg="Green").place(x=295,y=350)
root.mainloop()